name: Run Tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["*"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 4
      fail-fast: false
      matrix:
        version: ["5.2", "latest"]
        os: [macos-latest, windows-latest, ubuntu-latest]
    steps:
      - uses: actions/checkout@v5
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
      - uses: BradyAJohnston/setup-blender@v5
        with:
          version: ${{ matrix.version }}
      - name: Install test dependencies
        shell: bash
        run: |
          blender -b --python-expr "import sys, subprocess; subprocess.check_call([sys.executable, '-m', 'pip', 'install', '-e', '.[test]'])"
      - name: Run Tests in Blender
        shell: bash
        run: |
          blender -b --python-expr "import sys, subprocess; subprocess.check_call([sys.executable, '-m', 'pytest', '-vv', 'tests', '--cov', '--cov-report=xml'])"

